version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: ./truck_search/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./truck_search/.env
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ../data:/app/data
    depends_on:
      - db
