# Generated by Django 4.2.7 on 2024-03-21 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='trucks.location', to_field='zip'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Unique number must be in the format XXXXY, where X are digits from 1000 to 9999, Y is a capital letter', regex='^[0-9]{4}[A-Z]$')]),
        ),
    ]
